application: chongschat
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /script
  static_dir: script

- url: /stylesheets
  static_dir: stylesheets

- url: /canvas
  static_dir: canvas

- url: /.*
  script: chatroom.app

inbound_services:
- channel_presence

libraries:
- name: django
  version: "1.2"